### PR TITLE
Feature/pulssi 1148 master

### PR DESCRIPTION
**Pull request by timyllym**
- Update Organisations panel to work with Grafana 5.0
- Update dependencies

### CODE REVIEW

**Comment by timyllym** [comment]
You can install specific version of plugin. It should be no problem. We just need add to documentation that latest version works only with Grafana 5.0

**Comment by sapajune** [comment]
I thought so too but where can you see the different versions? Not in the repo it seems since there are no releases.

**Comment by timyllym** [comment]
Version info is maintained in Grafana Plugin pages:
https://grafana.com/plugins/digiapulssi-breadcrumb-panel

**Comment by sapajune** [comment]
Ok then. Let's document it there then. I assume we won't be maintaining version for older Grafana so documenting the compatibility should be enough.

**Pull request merged**
